'*.{js,ts,tsx,mjs,cjs}':
  - eslint --cache --fix --no-warn-ignored
  - bash -c "npm run build:ts && npm test"
package*.json:
  - prettier --write
  - npm dedupe
  - npx sort-package-json
'*.{json,yml,yaml},!package*.json':
  - prettier --write
