"*.{js,ts,tsx,mjs,cjs}":
  - eslint --cache --fix --no-warn-ignored
  - bash -c "npm run build:ts && npm test"
"*.{json,yml,yaml}":
  - eslint --cache --fix --no-warn-ignored
package*.json:
  - npm dedupe
  - npx sort-package-json
