files:
  - source: /shared/resources/locales/en.json
    translation: /shared/resources/locales/%two_letters_code%.json
  - source: /shared/resources/locales/commands/en.ts
    translation: /shared/resources/locales/commands/%two_letters_code%.ts
