files:
  - source: /src/resources/locales/en.json
    translation: /src/resources/locales/%two_letters_code%.json
  - source: /src/resources/locales/commands/en.js
    translation: /src/resources/locales/commands/%two_letters_code%.js
