# Use root/example as user/password credentials
version: '3.7'
services:
  db:
    container_name: db
    image: mariadb
    hostname: db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./database/mysql/data/:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "genesis"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  genesis:
    container_name: genesis
    image: genesis:latest
    restart: always
    depends_on:
      - db
    environment:
      # docker-compose-wait config
      WAIT_HOSTS: db:3306
      WAIT_BEFORE_HOSTS: 10
      WAIT_HOSTS_TIMEOUT: 60
      
      # Database config
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: genesis
      
      # Discord config
      TOKEN: 'discord bot token'
      PREFIX: '/'
      OWNER: '76685590585671680'
      HELP_URL: https://genesis.warframestat.us
      # INVITE_URL: https://bot.discord.io/genesis
      
      # Logging
      RAVEN_URL: 'raven logging url'
      LOG_LEVEL: ERROR
      # CONTROL_WH_TOKEN: 'webhook token'
      # CONTROL_WH_ID: 'webhook id'
      # BUG_WH_ID: 'webhook id for bug channel goes here'
      # BUG_WH_TOKEN: 'webhook token for bug channel goes here'

      # Feature flags, node config
      NODE_ENV: development
      SCOPE: BOT
      GAMES: UTIL,ROOMS,LOGGING

      # Sharding!!!
      SHARDS: 1
      LOCAL_SHARDS: 1
      SHARD_OFFSET: 0
      CLUSTER_ID: 0

      # Twitch notifications
      # TWITCH_CLIENT_ID: "--REQUIRED--"
      # TWITCH_USER_LOGIN: "warframe"
      # TWITCH_POLL_INTERVAL_MS: 10000

      # Tracking
      # DISCORD_CARBON_TOKEN: "Not used yet"
      # DISCORD_BOTS_WEB_USER: "Not used yet"
      # DISCORD_BOTS_WEB_TOKEN: "Not used yet"

      # CDN & Other configurables
      CDN_BASE_PATH: https://raw.githubusercontent.com/wfcd/warframe-items/development/data/
      API_BASE_PATH: https://api.warframestat.us
      WORLDSTATE_TIMEOUT: 60000
      
      # Embed configurables
      # LFG_EXPIRED_COLOR: 0xff0000
      # LFG_ACTIVE_COLOR: 0x00ff00
      # EMBED_URL: https://warframestat.us
      # EMBED_ICON_URL: https://warframestat.us/wfcd_logo_color.png
      # BASE_PRES_MSG: @Bot help
      # BASE_PRES_ACT: WATCHING